### PR TITLE
fix: keep version format consistent

### PR DESCRIPTION
**Pull request by edalex-yinzi**
Keep all versions in a consistent format.

### CODE REVIEW

**Comment by edalex-ian** [comment]
Hmmm, not sure about this one. You may want to check how those versions internally record their versions, as I think they're both still with the `r` based versioning - e.g. 2018.2r1 etc.

Other than aesthetics/consistency is there any technical reason you need to change these?

**Comment by edalex-yinzi** [comment]
Yes, technically, versioncheck.js assumes version is in YYYY.MM.DD format. So I think it may not be worth writing extra code just for these 2 versions.

**Comment by edalex-ian** [comment]
That's strange though, as isn't that the same value it used to get and use from the GitHub releases api?

And although you could change it, my concern is that it'll fail to match those older versions.

**Comment by edalex-yinzi** [comment]
Ah, I got it, that `format logic` was created after version 2019.1.1 so there won't be any problem for the previous version 2018.1 and 2019.1

**Pull request closed without merging**
