### PR TITLE
Add versions.json

### PR DESCRIPTION
**Pull request by edalex-yinzi**
I keep 3 attributes in versions.json.

`url`: release details url
`verison`: version number
`release_date`: release date without time

### CODE REVIEW

**Review by edalex-ian — CHANGES_REQUESTED** [review]
Great start @edalex-yinzi . Could we please change the following?

1. Please ensure you have all versions since we moved to year based versioning - you're missing a few, so see list at end;
2. As per your idea, let's remove the RC etc. ones;
3. Please sort the list by version (newest to oldest starting with 2022.1.0) - will make maintenance easier;
4. For the URL - which wasn't originally requested, but I like the idea - can we please use the release URL, e.g. for 2022.1.0 it would be `https://api.github.com/repos/openequella/openEQUELLA/releases/64077183`. I envisage in the future we may point this to the doco site etc, but for now this is better than using the tag; and
5. Could you please add another attribute for each entry called `ref` which holds a git ref pointing to the release - you should be able to easily grab the tag, and a commit would be even better.

Full list of versions:

2018.2
2019.1
2019.1.1
2019.1.2
2019.1.3
2019.1.4
2019.1.5
2019.1.6
2019.1.7
2019.1.8
2019.2.0
2019.2.1
2019.2.2
2019.2.3
2019.2.4
2019.2.5
2019.2.6
2020.1.0
2020.1.1
2020.1.2
2020.1.3
2020.1.4
2020.1.5
2020.1.6
2020.2.0
2020.2.1
2020.2.2
2021.1.0
2021.1.1
2021.1.2
2021.1.3
2021.1.4
2021.1.5
2021.2.0
2021.2.1
2021.2.2
2021.2.3
2022.1.0

**Comment by edalex-yinzi** [comment]
Thanks, Ian, I add a `html_url` since it's used in admin page.

**Review by edalex-ian — CHANGES_REQUESTED** [review]
That looks good @edalex-yinzi . :+1: 

But could you please make one more change - which I'm sorry, comes from a mistake I asked you to do. Could you please remove the `url` entries - just keep the `html_url` ones. Sorry.

Once they're gone, this will be good to merge.

**Comment by edalex-yinzi** [comment]
No worries. Removed.

**Review by edalex-ian — APPROVED** [review]
Thanks @edalex-yinzi , ready to merge.

**Pull request merged**
